# Generated by Django 3.1.7 on 2021-03-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128, verbose_name='型号')),
                ('maker', models.CharField(max_length=128, verbose_name='制造商')),
                ('year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(default=0, verbose_name='价格')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('desp', models.PositiveIntegerField(default=128, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
