# Generated by Django 3.1.7 on 2021-03-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('Name', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Sex', models.CharField(max_length=2)),
                ('Age', models.ImageField(upload_to='')),
            ],
        ),
    ]
