# Generated by Django 3.1.7 on 2021-03-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Sex', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('Tel', models.CharField(max_length=30)),
            ],
        ),
    ]
